# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b9a103fe249b659db1a3665c3c03e25dd341374d7d461535f6d5792130fa8b8f536958fee301cd83ad17417ee29c9d9c54af86a06bc187fc161f74cc5216617

test:
  secret_key_base: a5e335a91c56ade5cbce79284fa96f782af013d545b1a716be720db5aa7b50635b4bf93168ea93b1676b632034cd03273b7e9596a40e2962a9e278f1a9f8693f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
